name: GitHub Submodule Updates

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *' 

env:
  BASE_BRANCH: 'main'
  PR_LABEL: 'Create Release Environment'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate Access Token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ vars.PR_AUTO_UPDATE_CLIENT_ID }}
          private-key: ${{ secrets.PR_AUTO_UPDATE_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          submodules: true
          fetch-depth: 0

      - name: Update submodules, create branch, and push
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Pull latest submodule changes
          git submodule update --remote
          
          # Check if there are any changes to commit. If not, exit cleanly.
          if [ -z "$(git status --porcelain)" ]; then
            echo "No submodule changes detected."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "changed=true" >> $GITHUB_OUTPUT
          
          # Create and push new branch
          BRANCH_NAME="update-submodules-${GITHUB_RUN_ID}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          git checkout -b $BRANCH_NAME
          git commit -am "chore: update submodules"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create pull request and add label
        if: steps.commit.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: '${{ steps.commit.outputs.branch_name }}',
              base: process.env.BASE_BRANCH,
              title: `[Auto-generated] Submodule Updates ${process.env.GITHUB_RUN_ID}`,
              body: `Automated PR to update submodules to their latest remote commits.\n\nRun ID: ${process.env.GITHUB_RUN_ID}`,
            });
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.data.number,
              labels: [process.env.PR_LABEL]
            });
